# SPDX-License-Identifier: Apache-2.0
# Mosquitto configuration for fleet telemetry broker.
# Credentials are generated on first run via docker-entrypoint.

listener 1883
protocol mqtt

allow_anonymous false
password_file /mosquitto/config/passwd

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type warning
log_type error
log_type notice
