# SPDX-License-Identifier: Apache-2.0
name: Firmware Unit Tests

on:
  push:
    paths: ['firmware/**']
  pull_request:
    paths: ['firmware/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout v4.1.1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Build and run unit tests
        working-directory: firmware/tests
        run: |
          make clean
          make test
