# SPDX-License-Identifier: Apache-2.0
name: Python Lint

on:
  push:
    paths: ['sdk/**/*.py']
  pull_request:
    paths: ['sdk/**/*.py']

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout v4.1.1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      # actions/setup-python v5.3.0
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: '3.11'

      - name: Install ruff
        run: pip install ruff

      - name: Check formatting
        run: ruff format --check sdk/

      - name: Lint
        run: ruff check sdk/
